server:
  port: 8447
security:
  oauth2:
    client:
      scope: openid
      clientId: 
      clientSecret: 
      accessTokenUri: 
      userAuthorizationUri: 
      clientAuthenticationScheme: form    